// Hand-written types mirroring supabase/migrations/0001_init.sql and
// 0002_product_unit_size.sql. If the schema changes, update this alongside
// the migrations.

/** Matches the `products_unit_check` constraint in 0002_product_unit_size.sql. */
export const PRODUCT_UNITS = [
  "each",
  "kg",
  "g",
  "liter",
  "ml",
  "dozen",
  "pack",
  "box",
  "bag",
] as const;

export type ProductUnit = (typeof PRODUCT_UNITS)[number];

export type Category = {
  id: string;
  parent_id: string | null;
  name_en: string;
  name_ar: string;
  sort_order: number;
  created_at: string;
};

export type Product = {
  id: string;
  category_id: string;
  name_en: string;
  name_ar: string;
  description_en: string | null;
  description_ar: string | null;
  price: number;
  unit: ProductUnit;
  size: string | null;
  image_path: string | null;
  in_stock: boolean;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  updated_by: string | null;
};

export type Profile = {
  id: string;
  role: string;
  created_at: string;
};

/** A category with its direct subcategories attached, for nav trees. */
export type CategoryWithChildren = Category & {
  children: Category[];
};

/**
 * A temporary lower price for a product that expires on its own. At most
 * one per product — see 0003_discounts.sql.
 */
export type LimitedTimeDiscount = {
  id: string;
  product_id: string;
  new_price: number;
  starts_at: string;
  duration_days: number;
  /** Generated by the DB from `starts_at + duration_days`. */
  ends_at: string;
  created_at: string;
  updated_at: string;
  updated_by: string | null;
};

/** One "buy `min_quantity`+ for `price`" tier of a quantity discount. */
export type QuantityDiscountTier = {
  id: string;
  quantity_discount_id: string;
  min_quantity: number;
  price: number;
};

/** A product's tiered quantity pricing. At most one per product. */
export type QuantityDiscount = {
  id: string;
  product_id: string;
  created_at: string;
  updated_at: string;
  updated_by: string | null;
  /** Sorted ascending by `min_quantity`. */
  tiers: QuantityDiscountTier[];
};
